ASM = tasm /ML /M
CC = TCC -ml -a- -G -1 -f-
ANA = ana -DTURBO_C -ms -1 -c
# ŠÂ‹«•Ï”TMP‚ÌÅŒã‚Ì•¶Žš‚Í'\'‚Å‚È‚¢‚Æ‚¢‚¯‚È‚¢B
ASMDIR=$(TMP)

.c.obj:
	$(CC) -c $<
.ana.obj:
	$(ANA) -o$(ASMDIR) $<
	$(ASM) $(ASMDIR)$*.asm,$*,NUL,NUL
#.asm.obj:
#	$(ASM) $*,$*,NUL,NUL

OBJ =	\
	abx.obj	fil.obj	pri.obj	pri_fmt.obj

abx.exe : $(OBJ)
	$(CC) $(OBJ) $(LIB)
	copy abx.exe \tool\abx.exe

abx.obj  	: abx.c
fil.obj 	: fil.ana
pri.obj 	: pri.ana
pri_fmt.obj	: pri_fmt.as
	$(ASM) pri_fmt.as,pri_fmt.obj,NUL,NUL
