ASM = tasm /ML /M
CC = TCC -mc -a- -G -1 -f- -p
#CC = BCC -mc -a- -G -1- -f- -p -Ox
ANA = ana -DTURBO_C -ms -1 -c2
# ŠÂ‹«•Ï”TMP‚ÌÅŒã‚Ì•¶Žš‚Í'\'‚Å‚È‚¢‚Æ‚¢‚¯‚È‚¢B
# ASMDIR=$(TMP)
ASMDIR=.\\

.c.obj:
	$(CC) -c $<
.ana.obj:
	$(ANA) -o$(ASMDIR) $<
	$(ASM) $(ASMDIR)$*.asm,$*,NUL,NUL
#.asm.obj:
#	$(ASM) $*,$*,NUL,NUL

# TC4‚Ì‚Î‚©‚â‚ë`^^;
LIBS =	noehc.lib
#LIBS  =

OBJS =	\
	abx.obj 	tree.obj	fil.obj
#	pri.obj 	pri_fmt.obj

abx.exe : $(OBJS)
	$(CC) $(OBJS) $(LIBS)
	copy abx.exe \cmds\abx.exe
	copy abxg.cfg \cmds\abx.cfg
#	del  abx.exe

abx.obj  	: abx.c
tree.obj	: tree.c
fil.obj 	: fil.ana
#pri.obj 	: pri.ana
#pri_fmt.obj	: pri_fmt.as
#	$(ASM) pri_fmt.as,pri_fmt.obj,NUL,NUL
